export const ProjectList = [
  {
    name: "Pc Monkey",
    image: "https://i.ibb.co/n6GLvrG/pc-monkey.png",
    img1: "https://i.ibb.co/NnXynGY/pc-mon-2.png",
    img2: "https://i.ibb.co/FWyR0nc/pc-mon-3.png",
    img3: "https://i.ibb.co/x7jN9jV/pc-mon-4.png",
    tech: "React, Tailwind, JavaScript, HTML, CSS, Firebase, React Router, React Toastify, DaisyUi, Stripe, MongoDB, Axios",
    desc: "This website is a pc parts manufacturing website, which sells parts of pc in wholesale. This website is made with React, Firebase, MongoDB, and Node.js. This is a fully responsive website. This website implements a full CRUD operation. All buttons here are functional. This site also has a Stripe payment gateway system implemented, users can pay for their ordered products by sample test cards. This site also has a separate dashboard for users and admin. JWT authorization was also implemented for API security.",
    live: "https://pc-monkey.web.app/",
    git: "https://github.com/hassanmehedi1/pc-monkey-app",
    details: "React Nodejs MongoDB Firebase Stripe Tailwind",
  },
  {
    name: "KhabarChai.com",
    image: "https://i.ibb.co/mt0bcZy/food-app.png",
    img1: "https://i.ibb.co/SJh5BRL/food1.png",
    img2: "https://i.ibb.co/KFQnFpS/food2.png",
    img3: "https://i.ibb.co/X4vjQ4R/food3.png",
    tech: "React, Tailwind, JavaScript, HTML, CSS, Firebase, React Router, React Toastify, MongoDB, Axios",
    desc: "KhabarChai.com is a food inventory MERN-Stack website with CRUD operation. (fully responsive). All buttons are functional here. Integrated 3rd-party components from Tailwind, DaisyUi & for elegant UI/UX. Upon login, a user can Deliver or Restock the food item quantity. Users can also add any food item. Jwt authorization is implemented on this site for which only authorized users can see his/her added items only.",
    live: "https://food-inventory-app.web.app/",
    git: "https://github.com/hassanmehedi1/food-inventory-app",
    details: "React Nodejs MongoDB Firebase Tailwind",
  },
  {
    name: "MERN Todo App",
    image: "https://i.ibb.co/vJtK8JR/Screenshot-26.png",
    img1: "https://i.ibb.co/vJtK8JR/Screenshot-26.png",
    img2: "https://i.ibb.co/jfWj3yM/Screenshot-27.png",
    img3: "https://i.ibb.co/ykbsN99/Screenshot-28.png",
    tech: "React, Bootstrap, JavaScript, Nodejs, MongoDB, Express, Mongoose, HTML, CSS, React Router, React Toastify",
    desc: "This is a simple todo list site. Where users can add tasks for any event, Update the tasks, Mark tasks as completed, Delete task. For designing Bootstrap CSS library was used.",
    live: "https://dainty-puffpuff-8e0dc2.netlify.app/",
    git: "https://github.com/hassanmehedi1/mern-todo-app",
    details: "React Node MongoDB Express React-Router",
  },
  {
    name: "Dream Photography",
    image: "https://i.ibb.co/tJt2g2V/dream-photo.png",
    img1: "https://i.ibb.co/M7mmNTT/dream1.png",
    img2: "https://i.ibb.co/X5L85bW/dream2.png",
    img3: "https://i.ibb.co/sWM4p53/dream3.png",
    tech: "React, Tailwind, JavaScript, HTML, CSS, Firebase, React Router, React Toastify",
    desc: "This is a photography event site. Where users can order for any event photography. Has total of 3 bundle pack.Each bundle has a dynamic route button. Firebase authentication was implemented for login and signup. For designing Tailwind CSS library was used.",
    live: "https://dream-photography-app.web.app/",
    git: "https://github.com/hassanmehedi1/dream-photography-app",
    details: "React Firebase Tailwind React-Router",
  },
  {
    name: "Review Loader",
    image: "https://i.ibb.co/TBprkFk/review-loader.png",
    img1: "https://i.ibb.co/R039dLK/review1.png",
    img2: "https://i.ibb.co/S7vXTGf/review3.png",
    img3: "https://i.ibb.co/tPbRn54/review2.png",
    tech: "React, Bootstrap, JavaScript, HTML, CSS, React Router,Recharts",
    desc: "This is SPA product review website. Used Bootstrap for styling. Has a review section for the users(not dynamic). React Charts was implemented in the dashboard route.",
    live: "https://review-loader.netlify.app/",
    git: "https://github.com/hassanmehedi1/review-loader-website",
    details: "React Bootstrap React-Router",
  },
  {
    name: "Loki Convention Center",
    image: "https://i.ibb.co/yWtBPBj/loki-convo.png",
    img1: "https://i.ibb.co/g6w1P9n/loki1.png",
    img2: "https://i.ibb.co/tmHnZNb/loki2.png",
    img3: "https://i.ibb.co/hZ9wm3S/loki3.png",
    tech: "Bootstrap, JavaScript, HTML, CSS",
    desc: "This is a SPA website. Bootstrap was used for designing this website. It has a nice looking carousel.",
    live: "https://mehedis-convention-center.netlify.app/",
    git: "https://github.com/hassanmehedi1/convention-center-website",
    details: "HTML CSS Bootstrap",
  },
  {
    name: "Photo Shop",
    image: "https://i.ibb.co/1d0zN7X/influ-pro.png",
    img1: "https://i.ibb.co/jGW5gfL/pro1.png",
    img2: "https://i.ibb.co/vwZ0M0b/pro2.png",
    img3: "https://i.ibb.co/DfRxwk1/pro3.png",
    tech: "Bootstrap, JavaScript, HTML, CSS",
    desc: "This is also a static product website. Designed by Bootstrap and CSS.",
    live: "https://products-for-influencers.netlify.app/",
    git: "https://github.com/hassanmehedi1/Event-Management",
    details: "HTML CSS Bootstrap",
  },
];
