export const ProjectList = [
  {
    name: "Pc Monkey",
    image: "https://i.ibb.co/n6GLvrG/pc-monkey.png",
    tech: "React, Tailwind, JavaScript, HTML, CSS, Firebase, React Router, React Toastify, DaisyUi, Stripe, MongoDB, Axios",
    desc: "This website is pc parts manufacturer who sell parts of pc in wholesale. This website is made with react, firebase, mongodb, express. this is a full responsive website. This website implements full CRUD operation. all buttons are functional here. This site also has a Stripe payment gateway system implemented, users can for their ordered products by sample test cards. This site also has a separate dashboard for user and admin.",
    live: "https://pc-monkey.web.app/",
    git: "https://github.com/hassanmehedi1/pc-monkey-app",
  },
  {
    name: "KahabarChai.com",
    image: "https://i.ibb.co/mt0bcZy/food-app.png",
    tech: "React, Tailwind, JavaScript, HTML, CSS, Firebase, React Router, React Toastify, MongoDB, Axios",
    desc: "KhabarChai.com is a food inventory MERN-Stack website with CRUD operation.(fully responsive), This website implements full CRUD operation. All buttons are functional here. Integrated 3rd-party components from Tailwind, DaisyUi & for elegent UI/UX. Upon login, a user can Deliver or Restock the food item quantity. Users can also add any food item. Jwt authorization is implemented on this site for which only authorized users can see his/her added items only.",
    live: "https://food-inventory-app.web.app/",
    git: "https://github.com/hassanmehedi1/food-inventory-app",
  },
  {
    name: "Dream Photography",
    image: "https://i.ibb.co/tJt2g2V/dream-photo.png",
    tech: "React, Tailwind, JavaScript, HTML, CSS, Firebase, React Router, React Toastify",
    desc: "This is a photography event site. Where users can order for any event photography. Has total of 3 bundle pack.Each bundle has a dynamic route button. Firebase authentication was implemented for login and signup.",
    live: "https://dream-photography-app.web.app/",
    git: "https://github.com/hassanmehedi1/dream-photography-app",
  },
  {
    name: "Review Loader",
    image: "https://i.ibb.co/TBprkFk/review-loader.png",
    tech: "React, Bootstrap, JavaScript, HTML, CSS, React Router,Recharts",
    desc: "This is SPA product review website. Used Bootstrap for styling. Has a review section for the users(not dynamic). React Charts was implemented in the dashboard route.",
    live: "https://review-loader.netlify.app/",
    git: "https://github.com/hassanmehedi1/review-loader-website",
  },
  {
    name: "Loki Convention Center",
    image: "https://i.ibb.co/yWtBPBj/loki-convo.png",
    tech: "Bootstrap, JavaScript, HTML, CSS",
    desc: "This is a SPA website. Bootstrap was used for designing this website. It has a nice looking carousel.",
    live: "https://mehedis-convention-center.netlify.app/",
    git: "https://github.com/hassanmehedi1/convention-center-website",
  },
  {
    name: "Photo Shop",
    image: "https://i.ibb.co/1d0zN7X/influ-pro.png",
    tech: "Bootstrap, JavaScript, HTML, CSS",
    desc: "This is also a static product website. Designed by Bootstrap and CSS.",
    live: "https://products-for-influencers.netlify.app/",
    git: "https://github.com/hassanmehedi1/Event-Management",
  },
];
